changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Features
      labels:
        - enhancement
      exclude:
        labels:
          - dependencies
          - bug
    - title: Bug Fixes
      labels:
        - bug
      exclude:
        labels:
          - dependencies
          - enhancement
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"