blank_issues_enabled: false
contact_links:
  - name: Questions and discussion
    url: https://github.com/carbonintensityio/green-scheduler/blob/main/CONTRIBUTING.md
    about: Please read CONTRIBUTING.md for how to get in touch and how to contribute.
