package io.carbonintensity.scheduler.micronaut;

import java.util.Objects;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

import io.carbonintensity.scheduler.ScheduledExecution;
import io.carbonintensity.scheduler.runtime.ScheduledInvoker;
import io.micronaut.context.BeanContext;
import io.micronaut.inject.BeanDefinition;
import io.micronaut.inject.ExecutableMethod;

/**
 * {@link ScheduledInvoker} that invokes a scheduled business method through the
 * {@link ExecutableMethod} generated by Micronaut at build time, i.e. without runtime reflection.
 */
class ExecutableMethodInvoker implements ScheduledInvoker {

    private final BeanContext beanContext;
    private final BeanDefinition<?> beanDefinition;
    private final ExecutableMethod<?, ?> method;
    private final boolean expectsScheduledExecution;

    ExecutableMethodInvoker(BeanContext beanContext, BeanDefinition<?> beanDefinition, ExecutableMethod<?, ?> method) {
        this.beanContext = Objects.requireNonNull(beanContext);
        this.beanDefinition = Objects.requireNonNull(beanDefinition);
        this.method = Objects.requireNonNull(method);
        this.expectsScheduledExecution = method.getArguments().length == 1;
    }

    @SuppressWarnings("unchecked")
    @Override
    public CompletionStage<Void> invoke(ScheduledExecution execution) {
        try {
            Object bean = beanContext.getBean((BeanDefinition<Object>) beanDefinition);
            var executableMethod = (ExecutableMethod<Object, Object>) method;
            if (expectsScheduledExecution) {
                executableMethod.invoke(bean, execution);
            } else {
                executableMethod.invoke(bean);
            }
            return CompletableFuture.completedFuture(null);
        } catch (Exception e) {
            return CompletableFuture.failedStage(e);
        }
    }

    // The scheduled method is invoked directly on the green scheduler's own job executor
    // (see SimpleScheduler), never on Micronaut's event loop, so it is always blocking from
    // Micronaut's point of view.
    @Override
    public boolean isBlocking() {
        return true;
    }
}
