name: Release

env:
  MAVEN_MIRROR: ${{ secrets.MAVEN_MIRROR }}
  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  COMMON_MAVEN_ARGS: "-e -B --activate-profiles release --settings .github/mvn-settings.xml --fail-at-end -Dno-format"

on:
  pull_request:
    types: [ closed ]
    paths:
      - '.github/project.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.merged == true}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Retrieve metadata
        uses: radcortez/project-metadata-action@main
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'
          local-file: 'true'

      - name: Configure Git author
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build artefact
        run: ./mvnw $COMMON_MAVEN_ARGS --file pom.xml -Drevision=${{steps.metadata.outputs.current-version}} deploy

      - name: Tag
        uses: hole19/git-tag-action@master
        env:
          TAG: 'v${{ steps.metadata.outputs.current-version }}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release and upload artefact
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}